// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXLdgFkFDYvgwQ8FKZMbT7ssnevuf1rQI',
    appId: '1:366012024248:web:60f255071853f8b2b1bb4d',
    messagingSenderId: '366012024248',
    projectId: 'farmer-connector',
    authDomain: 'farmer-connector.firebaseapp.com',
    storageBucket: 'farmer-connector.firebasestorage.app',
    measurementId: 'G-WNGH19P6BZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOITtm6vyqKweNYsyYmQNeC8Nyixtn7ro',
    appId: '1:366012024248:android:7c1f7934ba7d222fb1bb4d',
    messagingSenderId: '366012024248',
    projectId: 'farmer-connector',
    storageBucket: 'farmer-connector.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUHIvF44kONBe8p2PSQgOWqErl-ao9_RE',
    appId: '1:366012024248:ios:4a09ae9176eb8bf3b1bb4d',
    messagingSenderId: '366012024248',
    projectId: 'farmer-connector',
    storageBucket: 'farmer-connector.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUHIvF44kONBe8p2PSQgOWqErl-ao9_RE',
    appId: '1:366012024248:ios:4a09ae9176eb8bf3b1bb4d',
    messagingSenderId: '366012024248',
    projectId: 'farmer-connector',
    storageBucket: 'farmer-connector.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXLdgFkFDYvgwQ8FKZMbT7ssnevuf1rQI',
    appId: '1:366012024248:web:d7ead252f34eda11b1bb4d',
    messagingSenderId: '366012024248',
    projectId: 'farmer-connector',
    authDomain: 'farmer-connector.firebaseapp.com',
    storageBucket: 'farmer-connector.firebasestorage.app',
    measurementId: 'G-N7F0H6PWDQ',
  );
}
